Repository fahimahammed/DevUI, pull requests merged in 2025-10, with the labels that each got.

#46 fixes : Add Responsive Layout for Component Grid #8
  SEARCH_FILTER_ENHANCEMENT.md
  src/app/globals.css
  src/app/page.tsx
  src/components/ComponentCard.tsx
  src/components/ui/dialog.tsx
  src/data/components.tsx
Labels: pr-opened

#47 added Textarea component for multi-line text input
  package.json
  src/components/ui/progress.tsx
  src/components/ui/textarea.tsx
  src/data/components.tsx
Labels: pr-opened

#54 merged
  .github/workflows/release-please.yml.disabled
  .release-please-manifest.json
  release-please-config.json
Labels: pr-opened

#63 Awesome Header and Footer
  package-lock.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ui/BackToTopButton.tsx
Labels: pr-opened

#65 feat(ui): add Button loading state, enhance Card hover, and add glow utility
  src/app/globals.css
  src/components/ui/button.tsx
  src/components/ui/card.tsx
Labels: pr-opened

#66 feat(ThemeColorPicker): integrate live theme color picker across app with animated UI enhancements
  src/app/layout.tsx
  src/components/ui/ThemeColorPicker.tsx
Labels: pr-opened

#72 deploy
  package-lock.json
  src/app/globals.css
  src/app/page.tsx
  src/components/CodeBlock.tsx
  src/components/ComponentCard.tsx
  src/data/components.tsx
Labels: pr-opened

#80 About page now matched the Website Theme
  src/app/about/page.tsx
Labels: pr-opened

#84 Feature add back to top button
  package-lock.json
  src/app/docs/layout.tsx
  src/app/docs/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ui/BackToTopButton.tsx
  src/data/components.tsx
Labels: pr-opened

#110 adding sidebar
  src/app/sidebar-demo/page.tsx
  src/components/SidebarDemo.tsx
  src/components/ui/sidebar.tsx
  src/data/components.tsx
Labels: pr-opened

#113 UI/UX Improvements in Card & CodeBlock Components
  src/components/CodeBlock.tsx
  src/components/ComponentCard.tsx
Labels: pr-opened

#118 fix Browse Components button
  src/app/page.tsx
Labels: pr-opened

#119 Make button and badge colors dynamic
  src/components/ui/ThemeColorPicker.tsx
Labels: pr-opened

#120 add: MenuBar Component
  package-lock.json
  package.json
  src/components/ui/menubar.tsx
  src/data/components.tsx
Labels: pr-opened

#121 Add light/dark theme toggle in header
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/components/ui/ThemeColorPicker.tsx
Labels: pr-opened

#122 Refactored Code Snippet UI
  package-lock.json
  package.json
  src/components/CodeBlock.tsx
  src/components/ComponentCard.tsx
Labels: pr-opened

#130 V1.0.3
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/CodeBlock.tsx
  src/components/ComponentCard.tsx
  src/components/Header.tsx
  src/components/ui/ThemeColorPicker.tsx
Labels: pr-opened

#123 add: Drawer Component
  package-lock.json
  package.json
  src/components/ui/drawer.tsx
  src/data/components.tsx
Labels: pr-opened

#125 Rebuilt SearchBar, added Icon and Added a new Section for Contribution
  src/app/page.tsx
  src/components/CodeBlock.tsx
  src/components/ComponentCard.tsx
Labels: pr-opened

#127 feat: add templates feature request, but report, documentation update and pull request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_update.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr-opened

#142 fix: sync code with prod
  package-lock.json
  src/components/CodeBlock.tsx
Labels: pr-opened

#143 ADDED COMPONENT
  src/components/ui/file-upload.tsx
  src/data/components.tsx
Labels: pr-opened

#144 Feature/tooltip and fab components
  package-lock.json
  package.json
  src/components/ui/floating-action-button.tsx
  src/components/ui/tooltip.tsx
  src/data/components.tsx
Labels: pr-opened

#134 Add skeleton loading placeholders for ComponentCard#27
  package-lock.json
  package.json
  src/app/globals.css
  src/components/ComponentCard.tsx
  src/components/ui/skeleton.tsx
Labels: action-required, pr-opened, Merge conflict

#151 Fixed Dark Mode UI Issue
  src/components/ComponentCard.tsx
Labels: pr-opened

#159 chore: sync with main branch
  src/components/ComponentCard.tsx
  src/data/components.tsx
Labels: pr-opened

#160 chore(stage): release devui 1.0.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr-opened, autorelease: pending

#162 chore(main): release devui 1.0.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr-opened, autorelease: pending

#170 Added duplicate issue workflow
  .github/workflows/duplicate-issue.yml
Labels: pr-opened

#169 Enhance BackToTopButton with scroll progress indicator and improved
  src/components/ui/BackToTopButton.tsx
Labels: pr-opened

#171 Add: Sonner
  src/app/layout.tsx
  src/data/components.tsx
Labels: pr-opened

#174 chore: release 1.1.0
  .github/workflows/duplicate-issue.yml
  .github/workflows/release-please.yml
  .release-please-manifest.json
  PR_SUMMARY.md
  SEARCH_FILTER_ENHANCEMENT.md
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/components/ui/BackToTopButton.tsx
  src/components/ui/ThemeColorPicker.tsx
  src/data/components.tsx
Labels: pr-opened

#179 chore: sync with main branch
  src/data/components.tsx
Labels: pr-opened

#180 chore(main): release devui 1.2.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr-opened, autorelease: pending

#177 Feature/ai powered snippet
  src/app/docs/layout.tsx
  src/app/docs/page.tsx
  src/app/page.tsx
  src/components/ComponentSnippetCard.tsx
  src/components/Header.tsx
  src/data/components.tsx
  src/lib/componentSnippetGenerator.ts
Labels: pr-opened, Merge conflict

#172 Add: Tooltip
  src/components/ui/tooltip.tsx
  src/data/components.tsx
Labels: pr-opened, Merge conflict

#185 chore(main): release devui 1.3.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr-opened, autorelease: pending

#186 add: Typography
  src/data/components.tsx
Labels: pr-opened

#189 Fix color picker overflow, prevent hydration mismatches, and improve navigation
  src/app/page.tsx
  src/components/ComponentSnippetCard.tsx
  src/components/ui/ThemeColorPicker.tsx
Labels: pr-opened

#193 Implement URL-Based State Sync for Search and Category Filters on Components Page
  src/app/page.tsx
Labels: pr-opened
